#cloud-config

hostname: node_name
timezone: Europe/Paris

users:
  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: hashpassword
    ssh_authorized_keys:
      - sshkey

package_update: true
package_upgrade: true

packages:
  - ansible
  - sudo
  - curl
  - vim


final_message: |
  - Utilisateur admin créé
  - Ansible installé

